# Generated by Django 2.1.1 on 2018-09-27 16:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180927_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
