# Generated by Django 2.1.1 on 2018-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180927_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/no-img.jpg', height_field=400, upload_to='images/', width_field=400),
        ),
    ]
